chore: improve paths configuration and update "how to use" section
rolldown/rolldown pull request #568
Opened 2024-03-13 04:43 UTC by shonya3

### Description

1. Added the resolveTestCaseDir function to simplify the main loop code
2. Created the TESTS_ROOT_DIR constant and placed it at the top of the file for easy configuration from one place.
3. Updated the 'How to use this script' section.

Note: I want to point out, that first version of script had 
```js
// TODO Add a `.` prefix instead of skipping rest of the code.
```
![image](https://github.com/rolldown/rolldown/assets/79873939/bb6f6cdf-651e-4acf-9f9c-7b4a95b1b63d)
https://github.com/rolldown/rolldown/pull/105/commits/4a4a3f149cc3caf7a436ebe3a6b9b28019044dba

That script, as i understand, never generated prefixed with `.` directories for skipped tests.
But there are prefixed with dot skipped tests in  /crates/rolldown/tests/esbuild/
Maybe, it  was generated some other way.
Just want to point, maybe we still need to generate dot-prefixed directories for skipped tests. Maybe the deletion of the TODO comment was accidental.

### Test Plan

---

2024-03-13 12:45 UTC, hyf0 requested changes
Thank for your contribution. But I think the current implementation is more understandable than new one. This is an easy task and hard code is better than abstraction.

2024-03-13 13:11 UTC, shonya3 commented
Got it. It is about the function as I understand. Is the "How to use this script" part fine?

2024-03-13 15:11 UTC, shonya3 commented
Now, this is good and clear, i like this one personally!

2024-03-15 05:59 UTC, hyf0 approved these changes
Good!

2024-03-15 06:37 UTC, merged