perf: fast drop LinkStageOutput
rolldown/rolldown pull request #842
Opened 2024-04-12 08:40 UTC by underfin

### Description

2024-04-12 11:27 UTC, hyf0 commented
1. What's the optimization for? Rust or Node performance?

- If this is only for rust performance, we don't need this due to rust users could have their own `fast-drop` and drop our bundler
  - The reason we don't need this is that I think it's not our responsibility to do this optimization, since it could be done in user-land.
  - Second, this create threads implicitly in `drop` method
    - Implicitly here is bad. You couldn't predict creating thread behaviors by looking into the control flow.
    - it also can't be turned off. If users don't want this behavior, they need to either give up rolldown or raise a PR. So it doesn't make scene in the first place, especially user could this optimization on their own.

- If this only for node performance
  - You need a benchmark data to show that this is worth it for such a big change.
  - The changed code should be limited to `rolldown_binding`

2. How this optimization works?

Dropping data to another thread may show advantage on multiple time build but bad for one-time usage such as cli.

--- 

Saw you making this a draft, not worth for me to continue writing this.

2024-04-12 12:15 UTC, underfin commented
I'm finding why the ci benchmark is not changed. The js benchmark makes it difficult to see changes at local, but the rust benchmark will see the result. The pr branch is 180 ms compared to main branch 200 ms for threejs10x.

> If this is only for rust performance, we don't need this due to rust users could have their own fast-drop and drop our bundler

It is a Rust problem because we never drop memory manually, it depends on Rust runtime. The problem is `Module/AsT` will be used at rolldown everywhere, the drop action happened at the final process, but the data is larger, it take 20% times to drop it, and it will block the main thread.

> How this optimization works

The performance is due to has something to do before quit the main thread(drop data),  move the action of drop data to other thread will run it and other something in parallel. [Here](https://news.ycombinator.com/item?id=23362518) has some detail for it.

2024-04-12 12:26 UTC, Boshen commented
The technique is legit. But maybe don't call it `fast_drop`, call it `drop_in_another_thread`?

2024-04-12 12:28 UTC, Boshen commented
To show evidence, you should use [Mac Xcode Instruments](https://web-infra-dev.github.io/rspack-dev-guide/profiling/intro.html#mac-xcode-instruments) and see if your CPUs are occupied with drops in the end.

2024-04-12 15:28 UTC, hyf0 requested changes

2024-04-12 15:28 UTC, hyf0 commented on crates/rolldown/src/drop_in_another_thread.rs
> +fn drop_in_another_thread<T>(src: T)
Move this to `rolldown_utils` or `rolldown_binding`.

2024-04-12 15:28 UTC, hyf0 commented on crates/rolldown/src/drop_in_another_thread.rs
> +impl Drop for Symbols {
Apply this on `Bundler` in `rolldown_binding`. Revert all changes in `rolldown`.

2024-04-12 15:30 UTC, hyf0 commented
> Dropping data to another thread may show advantage on multiple time build but bad for one-time usage such as cli.

With that being said, we probably could add a flag to show we are running in `cli` mode and we could call `std::mem:forget` instead of `drop_in_another_thread` on the bundler. Probably would be more faster.

2024-04-13 07:17 UTC, hyf0 commented on crates/rolldown/src/drop_in_another_thread.rs
> +fn drop_in_another_thread<T>(src: T)
Thinking back again. Guess it would be ok stay in `rolldown` crate.

2024-04-13 07:19 UTC, hyf0 commented on crates/rolldown/src/drop_in_another_thread.rs
> +impl Drop for Symbols {
However, I still think should do this explicitly rather do it in `drop` method.

2024-04-13 07:52 UTC, Brooooooklyn commented
Using `std::mem::forget` is absolutely a footgun. If you don't perform any memory release operations during a large project build, it will lead to OOM issues more frequently, especially in memory-constrained environments like GitHub Actions and Vercel build. Introducing more complex memory management mechanisms, such as GC algorithms or LRU, would significantly increase the complexity of memory management and the likelihood of bugs.

I also oppose manually spawning memory to another thread for release internally; on some platforms, like wasm32, this approach would be counterproductive.

2024-04-13 08:08 UTC, hyf0 commented on crates/rolldown/src/drop_in_another_thread.rs
> +    drop_in_another_thread(std::mem::take(self));
I'm not sure, but does this cause infinity loop? Every `drop` on `Self` will create a new `Self` and when the new `Self` is dropped another `Self` will be created again.

We end up create infinity threads on infinity `Self`.

2024-04-13 08:10 UTC, hyf0 commented
Overall, I think it's value, rspack use this optimization and has some improment. However as @Brooooooklyn said, it's not a best way in any situation, so what we need here is only apply this optimization in some conditions.

2024-04-15 08:03 UTC, closed without merging