feat: add test cases for esbuild packagejson
rolldown/rolldown pull request #969
Opened 2024-04-24 12:46 UTC by zhusjfaker

### Description

base the https://github.com/rolldown/rolldown/issues/783 issue link 

i have migrate  78 case in esbuild main branch for rolldown esbuild packagejson fold 

but the process has not been finished 

maybe i will finish it at the end of the April

2024-04-24 12:50 UTC, zhusjfaker commented
Fixes #783

2024-04-24 12:57 UTC, hyf0 requested changes

2024-04-24 12:57 UTC, hyf0 commented on crates/rolldown/tests/esbuild/packagejson/TestPackageJsonBadMain/node_modules/demo-pkg/package.json
Please use  snake_case here. Change `TestPackageJsonBadMain` to `bad_main`.

2024-04-24 12:57 UTC, hyf0 commented
All looks well. Well done!

2024-04-24 12:59 UTC, hyf0 commented
> but the process has not been finished

I suggest you could merge the current added tests. However, it's also fine that if you want merge them all together in a single PR.

If you are ready to merge the PR, just undraft this PR and I'll starting to review or and merge it.

2024-04-24 13:04 UTC, zhusjfaker commented on crates/rolldown/tests/esbuild/packagejson/TestPackageJsonBadMain/node_modules/demo-pkg/package.json
ok

2024-04-25 02:24 UTC, zhusjfaker commented
> > but the process has not been finished
> 
> I suggest you could merge the current added tests. However, it's also fine that if you want merge them all together in a single PR.
> 
> If you are ready to merge the PR, just undraft this PR and I'll starting to review or and merge it.

ok

2024-04-25 16:21 UTC, zhusjfaker commented
```golang

func TestPackageJsonNodePathsIssue2752(t *testing.T) {
	packagejson_suite.expectBundled(t, bundled{
		files: map[string]string{
			"/src/entry.js": `
				import "pkg1"
				import "pkg2"
				import "@scope/pkg3/baz"
				import "@scope/pkg4"
			`,
			"/usr/lib/pkg/pkg1/package.json":          `{ "main": "./foo.js" }`,
			"/usr/lib/pkg/pkg1/foo.js":                `console.log('pkg1')`,
			"/lib/pkg/pkg2/package.json":              `{ "exports": { ".": "./bar.js" } }`,
			"/lib/pkg/pkg2/bar.js":                    `console.log('pkg2')`,
			"/var/lib/pkg/@scope/pkg3/package.json":   `{ "browser": { "./baz.js": "./baz-browser.js" } }`,
			"/var/lib/pkg/@scope/pkg3/baz-browser.js": `console.log('pkg3')`,
			"/tmp/pkg/@scope/pkg4/package.json":       `{ "exports": { ".": { "import": "./bat.js" } } }`,
			"/tmp/pkg/@scope/pkg4/bat.js":             `console.log('pkg4')`,
		},
		entryPaths: []string{"/src/entry.js"},
		options: config.Options{
			Mode:          config.ModeBundle,
			AbsOutputFile: "/out.js",
			AbsNodePaths: []string{
				"/usr/lib/pkg",
				"/lib/pkg",
				"/var/lib/pkg",
				"/tmp/pkg",
			},
		},
	})
}
```

This case simulates a problem that occurs with a global module lookup, and I can't reproduce it too well in the current hard disk project, so I didn't migrate this case. 

@hyf0

2024-04-25 16:23 UTC, zhusjfaker commented
Except for TestPackageJsonNodePathsIssue2752 I've migrated all the other files needed for the test cases, specifically how to set up the '_config.json' against the product of esbuild How to go about combining the rolldown comparisons, including reporting errors. I still need to discuss with you.   @hyf0

2024-04-25 16:28 UTC, hyf0 commented
> Except for TestPackageJsonNodePathsIssue2752 I've migrated all the other files needed for the test cases, specifically how to set up the '_config.json' against the product of esbuild How to go about combining the rolldown comparisons, including reporting errors. I still need to discuss with you. @hyf0

Just follow how https://github.com/rolldown/rolldown/issues/783 did.

For `_config.json`, you could references:
- https://rolldown.rs/contrib-guide/testing#how-test-cases-are-defined
- Other existed `_config.json`

2024-04-25 16:32 UTC, hyf0 commented
> ```go
> func TestPackageJsonNodePathsIssue2752(t *testing.T) {
> 	packagejson_suite.expectBundled(t, bundled{
> 		files: map[string]string{
> 			"/src/entry.js": `
> 				import "pkg1"
> 				import "pkg2"
> 				import "@scope/pkg3/baz"
> 				import "@scope/pkg4"
> 			`,
> 			"/usr/lib/pkg/pkg1/package.json":          `{ "main": "./foo.js" }`,
> 			"/usr/lib/pkg/pkg1/foo.js":                `console.log('pkg1')`,
> 			"/lib/pkg/pkg2/package.json":              `{ "exports": { ".": "./bar.js" } }`,
> 			"/lib/pkg/pkg2/bar.js":                    `console.log('pkg2')`,
> 			"/var/lib/pkg/@scope/pkg3/package.json":   `{ "browser": { "./baz.js": "./baz-browser.js" } }`,
> 			"/var/lib/pkg/@scope/pkg3/baz-browser.js": `console.log('pkg3')`,
> 			"/tmp/pkg/@scope/pkg4/package.json":       `{ "exports": { ".": { "import": "./bat.js" } } }`,
> 			"/tmp/pkg/@scope/pkg4/bat.js":             `console.log('pkg4')`,
> 		},
> 		entryPaths: []string{"/src/entry.js"},
> 		options: config.Options{
> 			Mode:          config.ModeBundle,
> 			AbsOutputFile: "/out.js",
> 			AbsNodePaths: []string{
> 				"/usr/lib/pkg",
> 				"/lib/pkg",
> 				"/var/lib/pkg",
> 				"/tmp/pkg",
> 			},
> 		},
> 	})
> }
> ```
> 
> This case simulates a problem that occurs with a global module lookup, and I can't reproduce it too well in the current hard disk project, so I didn't migrate this case.
> 
> @hyf0

That's fine. Make sure you update `https://github.com/rolldown/rolldown/blob/main/crates/rolldown/tests/esbuild/packagejson/tests.txt` correctly.

2024-04-25 16:38 UTC, hyf0 commented on crates/rolldown/tests/esbuild/packagejson/TestPackageJsonBadMain/node_modules/demo-pkg/package.json
Following the naming pattern

```
TestPackageJsonBadMain => `bad_main`
TestPackageJsonSyntaxErrorComment => `synxtax_error_comment`
TestPackageJsonSyntaxErrorTrailingComma => `synxtax_error_trailing_comma`
```

2024-04-25 16:39 UTC, hyf0 commented on crates/rolldown/tests/esbuild/packagejson/test_package_json_bad_main/src/entry.js
Following the naming pattern

```
TestPackageJsonBadMain => `bad_main`
TestPackageJsonSyntaxErrorComment => `synxtax_error_comment`
TestPackageJsonSyntaxErrorTrailingComma => `synxtax_error_trailing_comma`
```

`crates/rolldown/tests/esbuild/packagejson/test_package_json_bad_main` should be `crates/rolldown/tests/esbuild/packagejson/bad_main`

2024-04-25 16:43 UTC, hyf0 commented on crates/rolldown/tests/esbuild/packagejson/TestPackageJsonBadMain/node_modules/demo-pkg/package.json
Well. I think again. The current naming of this PR is fine. Ignore this comment.

2024-04-25 16:44 UTC, hyf0 commented on crates/rolldown/tests/esbuild/packagejson/test_package_json_bad_main/src/entry.js
Ignore this comment https://github.com/rolldown/rolldown/pull/969#discussion_r1579819015

2024-04-25 17:06 UTC, zhusjfaker commented on crates/rolldown/tests/esbuild/packagejson/TestPackageJsonBadMain/node_modules/demo-pkg/package.json
> Well. I think again. The current naming of this PR is fine due there is a case that `TestCommonJSVariableInESMTypeModule` doesn't have the prefix `TestPackageJson`. So just ignore this comment.

ok

2024-04-27 11:31 UTC, hyf0 commented
If you feel it's difficult to write testing configs, I could take the PR from here and write those config. That's fine.

2024-04-28 12:39 UTC, zhusjfaker commented
I've got all the _config.json ready to go but found some issues with the Resolver for the current rolldown, do I need to fix it. I have prefixed all the problematic folders with “.” added the modifier, but the test won't skip it and still reports an error?  

@hyf0

2024-04-28 12:40 UTC, zhusjfaker commented
And now the judgment exception is just a simple boolean, is it necessary to add the exact error message to determine whether the error, and the capture of the same, in addition to build the content of the result of the assertion, whether it is also possible to configure through the config.json to go?

2024-04-28 12:43 UTC, hyf0 commented on crates/rolldown/tests/esbuild/packagejson/tests.txt
Could you delete that tests you have added in this PR?

2024-04-28 12:44 UTC, zhusjfaker commented on crates/rolldown/tests/esbuild/packagejson/tests.txt
ok

2024-04-28 12:46 UTC, zhusjfaker commented on crates/rolldown/tests/esbuild/packagejson/tests.txt
i have deleted  the case which i have add it in rolldown test folder

2024-04-28 13:10 UTC, hyf0 approved these changes
Great works! Thank you!

2024-04-28 13:18 UTC, merged